import { EventData } from '../types';

export const SAMPLE_EVENT: EventData = {
  id: 'barcelona-trip-2026',
  title: 'Barcelona Getaway',
  baseCurrency: 'EUR',
  createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
  participants: [
    {
      id: 'p-max',
      eventId: 'barcelona-trip-2026',
      name: 'Max',
      avatarColor: '#3B82F6',
      createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    },
    {
      id: 'p-sarah',
      eventId: 'barcelona-trip-2026',
      name: 'Sarah',
      avatarColor: '#10B981',
      createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    },
    {
      id: 'p-alex',
      eventId: 'barcelona-trip-2026',
      name: 'Alex',
      avatarColor: '#F59E0B',
      createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    },
    {
      id: 'p-elena',
      eventId: 'barcelona-trip-2026',
      name: 'Elena',
      avatarColor: '#EC4899',
      createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      eventId: 'barcelona-trip-2026',
      payerId: 'p-max',
      description: 'AirBnb Sagrada Familia',
      originalAmount: 480.0,
      originalCurrency: 'EUR',
      exchangeRate: 1.0,
      baseAmount: 480.0,
      isItemized: false,
      date: new Date(Date.now() - 3600 * 1000 * 36).toISOString(),
      createdAt: new Date(Date.now() - 3600 * 1000 * 36).toISOString(),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 36).toISOString(),
      splits: [
        { participantId: 'p-max', computedBaseAmount: 120.0 },
        { participantId: 'p-sarah', computedBaseAmount: 120.0 },
        { participantId: 'p-alex', computedBaseAmount: 120.0 },
        { participantId: 'p-elena', computedBaseAmount: 120.0 },
      ],
    },
    {
      id: 'exp-2',
      eventId: 'barcelona-trip-2026',
      payerId: 'p-sarah',
      description: 'Dinner at Can Culleretes',
      originalAmount: 96.0,
      originalCurrency: 'EUR',
      exchangeRate: 1.0,
      baseAmount: 96.0,
      isItemized: true,
      taxAmount: 8.0,
      tipAmount: 10.0,
      date: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
      createdAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
      lineItems: [
        { id: 'li-1', title: 'Paella Valenciana (x2)', amount: 42.0, consumerIds: ['p-max', 'p-sarah', 'p-alex'] },
        { id: 'li-2', title: 'Tapas & Sangria', amount: 36.0, consumerIds: ['p-max', 'p-sarah', 'p-elena'] },
      ],
      splits: [
        { participantId: 'p-max', computedBaseAmount: 32.0 },
        { participantId: 'p-sarah', computedBaseAmount: 32.0 },
        { participantId: 'p-alex', computedBaseAmount: 17.23 },
        { participantId: 'p-elena', computedBaseAmount: 14.77 },
      ],
    },
    {
      id: 'exp-3',
      eventId: 'barcelona-trip-2026',
      payerId: 'p-alex',
      description: 'Duty-free Snacks & Drinks',
      originalAmount: 54.25,
      originalCurrency: 'USD',
      exchangeRate: 0.921659, // 1 USD = 0.921659 EUR
      baseAmount: 50.0,
      isItemized: false,
      date: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      splits: [
        { participantId: 'p-alex', computedBaseAmount: 25.0 },
        { participantId: 'p-elena', computedBaseAmount: 25.0 },
      ],
    },
  ],
  settlements: [],
  activityLogs: [
    {
      id: 'act-1',
      eventId: 'barcelona-trip-2026',
      actorId: 'p-max',
      action: 'EVENT_CREATED',
      details: { title: 'Barcelona Getaway', baseCurrency: 'EUR' },
      createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    },
    {
      id: 'act-2',
      eventId: 'barcelona-trip-2026',
      actorId: 'p-max',
      action: 'EXPENSE_CREATED',
      details: { description: 'AirBnb Sagrada Familia', amount: 480.0, currency: 'EUR' },
      createdAt: new Date(Date.now() - 3600 * 1000 * 36).toISOString(),
    },
    {
      id: 'act-3',
      eventId: 'barcelona-trip-2026',
      actorId: 'p-sarah',
      action: 'EXPENSE_CREATED',
      details: { description: 'Dinner at Can Culleretes', amount: 96.0, currency: 'EUR', itemized: true },
      createdAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    },
    {
      id: 'act-4',
      eventId: 'barcelona-trip-2026',
      actorId: 'p-alex',
      action: 'EXPENSE_CREATED',
      details: { description: 'Duty-free Snacks & Drinks', amount: 54.25, currency: 'USD', baseAmount: 50.0 },
      createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    },
  ],
};
